// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gettree_cpp
List gettree_cpp(arma::vec y, arma::mat X, double minlossimprove, int minsize);
RcppExport SEXP _ORTdenoise_gettree_cpp(SEXP ySEXP, SEXP XSEXP, SEXP minlossimproveSEXP, SEXP minsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type minlossimprove(minlossimproveSEXP);
    Rcpp::traits::input_parameter< int >::type minsize(minsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(gettree_cpp(y, X, minlossimprove, minsize));
    return rcpp_result_gen;
END_RCPP
}
// TreetomatPixelSIMD
NumericVector TreetomatPixelSIMD(List tree, NumericVector img, IntegerVector dims, double smband, int nSteps);
RcppExport SEXP _ORTdenoise_TreetomatPixelSIMD(SEXP treeSEXP, SEXP imgSEXP, SEXP dimsSEXP, SEXP smbandSEXP, SEXP nStepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type img(imgSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< double >::type smband(smbandSEXP);
    Rcpp::traits::input_parameter< int >::type nSteps(nStepsSEXP);
    rcpp_result_gen = Rcpp::wrap(TreetomatPixelSIMD(tree, img, dims, smband, nSteps));
    return rcpp_result_gen;
END_RCPP
}
// ssim
double ssim(SEXP img1_, SEXP img2_, double K1, double K2, int win_size);
RcppExport SEXP _ORTdenoise_ssim(SEXP img1_SEXP, SEXP img2_SEXP, SEXP K1SEXP, SEXP K2SEXP, SEXP win_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type img1_(img1_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type img2_(img2_SEXP);
    Rcpp::traits::input_parameter< double >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< double >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< int >::type win_size(win_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ssim(img1_, img2_, K1, K2, win_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ORTdenoise_gettree_cpp", (DL_FUNC) &_ORTdenoise_gettree_cpp, 4},
    {"_ORTdenoise_TreetomatPixelSIMD", (DL_FUNC) &_ORTdenoise_TreetomatPixelSIMD, 5},
    {"_ORTdenoise_ssim", (DL_FUNC) &_ORTdenoise_ssim, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ORTdenoise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
