# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gettree_cpp <- function(y, X, minlossimprove = 0.01, minsize = 1L) {
    .Call(`_ORTdenoise_gettree_cpp`, y, X, minlossimprove, minsize)
}

TreetomatPixelSIMD <- function(tree, img, dims, smband, nSteps = 10000L) {
    .Call(`_ORTdenoise_TreetomatPixelSIMD`, tree, img, dims, smband, nSteps)
}

ssim <- function(img1_, img2_, K1 = 0.01, K2 = 0.03, win_size = 7L) {
    .Call(`_ORTdenoise_ssim`, img1_, img2_, K1, K2, win_size)
}

